### ISSUE TITLE
Step missing in minimal Linux kernel build

### ISSUE THREAD

**Issue by hb9cwp** [jboero/nomadinit#1]
At least on Ubuntu/Debian, without the additional step in the 3rd line below, ```make kvm_guest.config``` in 4th line from the README.md fails because there is no ```.config``` input file yet:
```
git clone --depth=1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
cd linux
make allnoconfig
make kvm_guest.config
make -j$(nproc)
```

Not being a Linux specialist, I have taken "allnoconfig" from the examples in [How To Build A Custom Linux Kernel For Qemu Using Docker](https://mgalgs.github.io/2021/03/23/how-to-build-a-custom-linux-kernel-for-qemu-using-docker.html).
With this additional step, I am able to build minimal kernels-5.8 (of which you had been using a release candidate) and -5.16 (current release) which boots in qemu (and loads a RAM file system with BusyBox).

However, I have still to integrate your minimal init instead of a initramfs, in order to be able to validate that NomadOS/HashiOS actually loads and starts.

**Comment by jboero** [comment]
Awesome thanks for the tip.  Yes as an ex-RedHatter I always tend to work with Fedora so appreciate the distro support.
