### ISSUE TITLE
Figure HashiStack "upside-down"

### ISSUE THREAD

**Issue by hb9cwp** [jboero/nomadinit#3]
This is the figure from the bottom of the White Paper "[Unlocking the Cloud Operating Mode](https://www.hashicorp.com/cloud-operating-model)l", turned upside-down, with steps of bootstrap process added. 

![image](https://user-images.githubusercontent.com/2629503/159451626-4106c7a2-162b-48b6-9a64-935d64b67dfc.png)

Admittedly, the outcome is somewhat "butchered" the shading of the stack etc., but that should be easy for designers who have the native graphic objects. Done in draw.io, file is available on request.

**Comment by jboero** [comment]
Oh wow this is awesome.  Thanks for the undertaking!
